In [1]:
import torch

In [2]:
from pytorch101 import take_one_elem_per_col

In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [4]:
idx0 = torch.arange(x.shape[1])

In [6]:
print(idx0)

tensor([0, 1, 2])


In [7]:
idx1 = torch.tensor([1,0,3])

In [9]:
x[idx1,idx0]

tensor([ 4,  2, 12])

In [5]:
out = take_one_elem_per_col(x)

In [6]:
print(out)

tensor([ 4,  2, 12])


In [2]:
from pytorch101 import count_negative_entries

In [3]:
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100)

In [4]:
out = count_negative_entries(x0)
out1 = count_negative_entries(x1)
out2 = cout
print(out)

2
