In [1]:
import torch

In [2]:
from pytorch101 import take_one_elem_per_col

In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [4]:
idx0 = torch.arange(x.shape[1])

In [6]:
print(idx0)

tensor([0, 1, 2])


In [7]:
idx1 = torch.tensor([1,0,3])

In [9]:
x[idx1,idx0]

tensor([ 4,  2, 12])

In [5]:
out = take_one_elem_per_col(x)

In [6]:
print(out)

tensor([ 4,  2, 12])


In [2]:
from pytorch101 import make_one_hot

In [6]:
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100)

In [7]:
out = count_negative_entries(x0)
out1 = count_negative_entries(x1)
out2 = count_negative_entries(x2)
print(out)
print(out1)
print(out2)

2
0
4939


In [3]:

x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)

In [4]:
print(y0)

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])


In [8]:
import torch
x = torch.tensor([[2, 4, 3, 5], [3, 3, 5, 2]], dtype=torch.float32)
row_min_vals, row_min_idxs = x.min(dim)