##  PYTORCH FRAMEWORK

In [2]:
import torch
print(torch.__version__)

1.6.0


In [5]:
a = torch.tensor([1,2,3]) # create a multidimentional grid of value
print(a)

tensor([1, 2, 3])


In [16]:
print(a.dim()) # print rank() 

1


In [7]:
print(a.shape) # size of array

torch.Size([3])


In [8]:
print(type(a)) #type of multidimentional array

<class 'torch.Tensor'>


In [9]:
print(type(a[0]))

<class 'torch.Tensor'>


In [13]:
print(a[2].item()) # print value at the position of multidimentional array

3


In [14]:
print(type(a[1].item()))

<class 'int'>


In [15]:
print('before mutating')
print(a)
a[2] = 15
print('after mutating')
print(a)

before mutating
tensor([1, 2, 3])
after mutating
tensor([ 1,  2, 15])


## Create tensor with two or more dimentions

In [20]:
b = torch.tensor([[1,2,3],[4,5,5],[6,7,8]])
print(b)
print(b.dim()) #print rank base on function dim()
print(b.shape) #print size base on the attribute shape of b

tensor([[1, 2, 3],
        [4, 5, 5],
        [6, 7, 8]])
2
torch.Size([3, 3])


In [24]:
print('b[0,2]:',b[0,2]) # return tensor value of cell b[0,2] // access the element of multidimentional tensor

b[0,2]: tensor(3)


In [27]:
b[0,2] = 100 #mutating the cell b[0,2] with value of 8
# print the tensor
print(b)

tensor([[  1,   2, 100],
        [  4,   5,   5],
        [  6,   7,   8]])


## Check whether it is true of false

In [36]:
print('b is tensor?',torch.is_tensor(b))
print('size of b is 3x3?',b.shape == (3,3))

b is tensor? True
size of b is 3x3? True


##### torch.zeros #create a tensor with all zeros
##### torch.ones #create a tensor with all ones
##### torch.rand #create a uniform random number
##### torch.eye #create identity matrix

In [40]:
c = torch.zeros(4,5)
d = torch.ones(2,2)
e = torch.rand(3,3)
f = torch.eye(3,3)
print(c)
print(d)
print(e)
print(f)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.0945, 0.8448, 0.7698],
        [0.8281, 0.4021, 0.1148],
        [0.3611, 0.4227, 0.0435]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### torch.full() // fill a tensor with mxn matrix with desired number

In [49]:
g = torch.full((2,3,4),7,out=None,dtype=torch.int32)

print(g)
print('is g filled with all 7?',(g == 7).all().item() == 1)

tensor([[[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]]], dtype=torch.int32)
is g filled with all 7? True


In [53]:
#create a 64bit floating-point tensor of shape of (6) filled with evenly -spaced value between 10-20
h = torch.linspace(10,20,6,dtype=torch.float64)
print(h)

tensor([10., 12., 14., 16., 18., 20.], dtype=torch.float64)


###### slice index

In [57]:
a = torch.tensor([1,2,3,4,5])
print(a)
print(a[:])
print(a[:4])
print(a[3:])
print(a[::2])
print(a[-4:])
print(a[:-2])
print(a[-5::3])

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4])
tensor([4, 5])
tensor([1, 3, 5])
tensor([2, 3, 4, 5])
tensor([1, 2, 3])
tensor([1, 4])


###### slice for each dimensions

In [69]:
b= torch.tensor([[4,5,6,7,2],[2,4,1,5,7]])
print(b)
print(b[1,:])
print(b[:,3])
print(b[1:2,:1])
print(b[:,2:].shape)
print(b[:1,-3:])

tensor([[4, 5, 6, 7, 2],
        [2, 4, 1, 5, 7]])
tensor([2, 4, 1, 5, 7])
tensor([7, 5])
tensor([[2]])
torch.Size([2, 3])
tensor([[6, 7, 2]])


###### tensor clone

In [74]:
c = b[:,2:]
d = b[:,2:].clone() # doesn't affect even though original tensor has been changed
d[1,2] = 20
print(d)
print(c)
print(d.storage().data_ptr() == c.storage().data_ptr())# check whether the tensor that is same as the original or not 

tensor([[ 6,  7,  2],
        [ 1,  5, 20]])
tensor([[6, 7, 2],
        [1, 5, 7]])
False


##### Integer Tensor Indexing

In [3]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
idx = torch.tensor([0,0,2,1,1]) #create a tensor of shape(5,3) by reordering from a
print(a[idx])
idx = [2,1,0] #reverse columns in a
print(a[i,idx])
idx= [0,1,2] #get diagonal of tensor 
print(a[idx,idx])
a[idx,idx] = torch.tensor([11,22,33]) #set diagonal of tensor
print(a)
idx0= torch.arange(a.shape[0]) # return rows of a
idx1 = [2,0,1]
print(a[idx0,idx1]) # pick ele 3 of row 0, ele 1 of row 1, element 2 of row 2 and return 1 dimensional tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [7, 8, 9],
        [4, 5, 6],
        [4, 5, 6]])
tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])
tensor([1, 5, 9])
tensor([[11,  2,  3],
        [ 4, 22,  6],
        [ 7,  8, 33]])
tensor([3, 4, 8])


##### working with boolean tensor index

In [5]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
mask = (3 <= a) & (a < 8)
print(mask) # compare each element of a with condition
print(a[mask]) #select elements that is matched with mask
replace = (3 < a)
a[replace] = 0 #modify values whose condition are satisfied
print(a)

tensor([[False, False,  True],
        [ True,  True,  True],
        [ True, False, False]])
tensor([3, 4, 5, 6, 7])
tensor([[1, 2, 3],
        [0, 0, 0],
        [0, 0, 0]])


In [17]:
def make_one_hot(x):
  """
  Construct a tensor of one-hot-vectors from a list of Python integers.

  Input:
  - x: A list of N ints

  Returns:
  - y: A tensor of shape (N, C) where C = 1 + max(x) is one more than the max
       value in x. The nth row of y is a one-hot-vector representation of x[n];
       In other words, if x[n] = c then y[n, c] = 1; all other elements of y are
       zeros.
  """
  
  y = torch.zeros(len(x),1 + max(x))
  #n is the position
  #c is the value
  for n in range(len(x)):
    for c in x:
      if x[n] == c :
        y[n,c] = 1
  ##############################################################################
  # TODO: Complete the implementation of this function.                        #
  ##############################################################################
  # Replace "pass" statement with your code
  
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

In [18]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

Here is y0:
tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])

Here is y1:
tensor([[0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.]])
all checks pass!
